# fly.toml app configuration file generated for mogbomoya on 2023-09-20T14:37:51+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mogbomoya"
primary_region = "ams"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  APP_URL = "https://mogbomoya.fly.dev"
  DB_CONNECTION = "mysql"
  DB_DATABASE = "laravel-apps"
  DB_HOST = "aws-eu-west-2.connect.psdb.cloud"
  DB_PASSWORD = "pscale_pw_3djKolABDAAeHkaarAY95344LNx6iHSDTQdy1WNMJOy"
  DB_USERNAME = "w99wd3yv54jx5z4t6d9x"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MAIL_ENCRYPTION = "tls"
  MAIL_FROM_ADDRESS = "info@mogbomoya.com"
  MAIL_FROM_NAME = "${APP_NAME}"
  MAIL_HOST = "smtp.mailtrap.io"
  MAIL_MAILER = "smtp"
  MAIL_PASSWORD = "e3bd26eb3e776f"
  MAIL_PORT = "2525"
  MAIL_USERNAME = "81d0c04aaab16d"
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
